# ============================================================
# LearnFlow - Configuracion de la aplicacion
# ============================================================

# Servidor
server.port=8080

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/learnflow?useSSL=false&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=LearnFlowSecretKey2026SuperSecureTokenForJWTGeneration
app.jwt.expiration-ms=86400000
